### PR TITLE
initial Quiz commit

### PR DESCRIPTION
**Pull request by prerna2712**
Screenshot from 2021-10-01 22-22-27
)

This is the initial commit

### CODE REVIEW

**Comment by SayantaniDeb** [comment]
Looks good, I'll after merge after reviewing

**Comment by SayantaniDeb** [comment]
I'm sorry i'm not able to merge this. Can you try working on something else.

**Comment by prerna2712** [comment]
But can you tell why?

**Comment by SayantaniDeb** [comment]
The UI isn't suiting the game for instance. You can work more on the
colours and the graphics of the quiz.

**Pull request closed without merging**
